### ISSUE TITLE
Feature request: don't start web if the plugin is not enabled

### ISSUE THREAD

**Issue by Joshfindit** [linuxserver/docker-beets#19]
I'd rather not run the web interface.

This would also resolve https://github.com/linuxserver/docker-beets/issues/3

**Comment by sparklyballs** [comment]
that issue (#3) was resolved.

you could just not expose the port

**Comment by Joshfindit** [comment]
Would you accept a PR if it:

- Checked for `web` in the plugin list
- Only ran `s6-setuidgid abc beet web` if `web` was found
- Ran a placeholder if it was not found (`bash`, for example)

?

**Comment by laker-93** [comment]
This issue is not solved. Disabling the 'web' plugin does not stop the docker container from attempting to use the beet web command - causing an annoying error in the log. If @Joshfindit suggestion above could be implemented, that would be great.

**Comment by aqxa1** [comment]
This issue isn't just a cosmetic error since it causes significant idle CPU usage from repeatedly trying to launch the server. It went from using 40-50% idle CPU usage according to `docker stats` down to 0.01% with the `web` plugin enabled. Even just a warning in the documentation would be helpful.
